project:
  type: website
  output-dir: docs

website:
  title: "ğŸ…ğŸ¼ Advent of Code 2023"
  navbar:
    right:
      - icon: github
        aria-label: github
        href: https://github.com/ddanieltan/aoc2023-quarto
  page-footer:
    left: "ğŸ„ Merry Christmas! ğŸ„ | Made by [@ddanieltan](https://www.ddanieltan.com/)"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    smooth-scroll: true

# Code
code-line-numbers: false
code-overflow: wrap
code-copy: true

# Default author
author:
  - name: Daniel Tan
    url: https://www.ddanieltan.com


